export enum ContentTypeEnum {
  JSON = "application/json",
  MULTIPART = "multipart/form-data",
  FORM_URLENCODED = "application/x-www-form-urlencoded",
  TEXT_PLAIN = "text/plain",
  TEXT_HTML = "text/html",
  XML = "application/xml",
  JAVASCRIPT = "application/javascript",
  OCTET_STREAM = "application/octet-stream",
  PDF = "application/pdf",
  ZIP = "application/zip",
  PNG = "image/png",
  JPEG = "image/jpeg",
  GIF = "image/gif",
  WEBP = "image/webp",
  SVG = "image/svg+xml",
  WAV = "audio/wav",
  MP3 = "audio/mpeg",
  MPEG = "video/mpeg",
  MP4 = "video/mp4"
}